package profiling:profiling;

world bindings {
    import op: interface {
        perf-new-counter: func(
            ret-area-ptr: u32,
            sered-process-ptr: u32,
            sered-process-len: u32,
            sered-cpu-ptr: u32,
            sered-cpu-len: u32,
            sered-cfg-ptr: u32,
            sered-cfg-len: u32,
        );
        perf-enable-counter: func(
            ret-area-ptr: u32,
            counter-rid: u32
        );
        perf-disable-counter: func(
            ret-area-ptr: u32,
            counter-rid: u32
        );
        perf-reset-counter-count: func(
            ret-area-ptr: u32,
            counter-rid: u32
        );
        perf-get-counter-stat: func(
            ret-area-ptr: u32,
            counter-rid: u32
        );
    }
}
