package profiling:profiling;

world bindings {
    import op: interface {
        perf-counter-new: func(
            ret-area-ptr: u32,
            sered-process-ptr: u32,
            sered-process-len: u32,
            sered-cpu-ptr: u32,
            sered-cpu-len: u32,
            sered-cfg-ptr: u32,
            sered-cfg-len: u32,
        );
        perf-counter-enable: func(
            ret-area-ptr: u32,
            counter-rid: u32
        );
        perf-counter-disable: func(
            ret-area-ptr: u32,
            counter-rid: u32
        );
        perf-counter-reset-count: func(
            ret-area-ptr: u32,
            counter-rid: u32
        );
        perf-counter-stat: func(
            ret-area-ptr: u32,
            counter-rid: u32
        );
    }
}
