package profiling:strategy;

world bindings {
    import op: interface {
        log: func(info: string);
        exit: func();

        file-is-exist: func(path-ptr: u32, path-len: u32) -> u32;
        file-read: func(
            ret-area-ptr: u32,
            path-ptr: u32,
            path-len: u32
        );
        file-write: func(
            ret-area-ptr: u32,
            path-ptr: u32,
            path-len: u32,
            contents-ptr: u32,
            contents-len: u32
        );
        file-append: func(
            ret-area-ptr: u32,
            path-ptr: u32,
            path-len: u32,
            contents-ptr: u32,
            contents-len: u32
        );
    }
}
