package profiling:profiling;

world bindings {
    import op: interface {
        log: func(info-ptr: u32, info-len: u32);
        log-err: func(info-ptr: u32, info-len: u32);
        exit: func();
        drop-resource: func(rid: u32);
    }
}
